kind: Service
apiVersion: v1
metadata:
  name: cloud-native-ee
spec:
  selector:
    app: cloud-native-ee
  ports:
    - port: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: cloud-native-ee
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-native-ee
    spec:
      containers:
      - name: cloud-native-ee
        image: sebastian-daschner.com:1000/cloud-native-ee:7
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /opt/wildfly/modules/com/sebastian-daschner/configuration/main/properties
        livenessProbe:
          httpGet:
            path: /cloud-native-ee/resources/hello
            port: 8080
      volumes:
      - name: config-volume
        configMap:
          name: hello-config
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-config
data:
  application.properties: |
    hello.greeting=Hi
    hello.name=Kubernetes
