kind: Service
apiVersion: v1
metadata:
  name: cloud-native-ee
spec:
  selector:
    app: cloud-native-ee
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cloud-native-ee
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-native-ee
    spec:
      containers:
      - image: sebastian-daschner.com:1000/cloud-native-ee:1
        imagePullPolicy: IfNotPresent
        name: cloud-native-ee
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
